version: "3.8"
services:
    db:
        image: mysql:8.0.32
        container_name: "${CONTAINER_APP_NAME:-pedrosa-payments}-mysql"
        entrypoint: [
            '/entrypoint.sh',
            '--default-time-zone=UTC',
        ]
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "${CONTAINER_MYSQL_PORT:-3306}:3306"
        volumes:
            - .docker-volumes/mysql:/var/lib/mysql
            - .setup/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    cache:
        image: redis:7.0.7-alpine
        container_name: "${CONTAINER_APP_NAME:-pedrosa-payments}-redis"
        ports:
            - "${CONTAINER_REDIS_PORT:-6379}:6379"
        volumes:
            - .docker-volumes/redis:/data

    app:
        build:
            context: .
            dockerfile: ./.setup/php/Dockerfile
            args:
                CONTAINER_ENVIRONMENT: ${APP_ENV:-local}
                CONTAINER_TIMEZONE: ${APP_TIMEZONE:-UTC}
        image: pedrosalpr/${CONTAINER_APP_NAME:-pedrosa-payments}-${APP_ENV:-local}:${APP_VERSION:-latest}
        container_name: ${CONTAINER_APP_NAME:-pedrosa-payments}-${APP_ENV:-local}-${APP_VERSION:-latest}
        restart: unless-stopped
        links:
            - db
            - cache
        networks:
            - default
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${CONTAINER_HTTP_PORT:-80}:8080"
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
            - cache

    

